version: "3"

services:
  vote:
    image: jeromedecoster/vote
    volumes:
      - "./vote:/app"
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - redis
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend: {}